export function extractPlaygroundImports(content: string) {
  const imports = new Map<string, string>();

  const regex =
    /import\s+(\w+)\s+from\s+["']@site\/docs\/autogenerated\/playground\/([^"']+)\.mdx["'];?/g;

  for (const match of content.matchAll(regex)) {
    imports.set(match[1], match[2]);
  }

  return imports;
}

export function extractAutogeneratedMdxImports(content: string) {
  const imports = new Map<string, string>();

  const regex =
    /import\s+(\w+)\s+from\s+["']@site\/docs\/autogenerated\/([^"']+)\.mdx["'];?/g;

  for (const match of content.matchAll(regex)) {
    imports.set(match[1], match[2]);
  }

  return imports;
}

export function extractSiteDocsImports(content: string) {
  const imports = new Map<string, string>();

  const regex =
    /import\s+(\w+)\s+from\s+["']@site\/docs\/([^"']+)\.(md|mdx)["'];?/g;

  for (const match of content.matchAll(regex)) {
    imports.set(match[1], `${match[2]}.${match[3]}`);
  }

  return imports;
}

export function stripFrontmatter(content: string) {
  return content.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, '');
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function extractImportedIdentifiers(importClause: string) {
  const identifiers: string[] = [];
  const clause = importClause.trim();

  const namedImportMatch = clause.match(/\{([^}]+)\}/);
  if (namedImportMatch) {
    const namedImports = namedImportMatch[1]
      .split(',')
      .map((token) => token.trim())
      .filter(Boolean);

    for (const token of namedImports) {
      const aliasMatch = token.match(/^\w+\s+as\s+(\w+)$/);
      if (aliasMatch) {
        identifiers.push(aliasMatch[1]);
      } else {
        identifiers.push(token);
      }
    }
  }

  const defaultImportPart = clause
    .replace(/\{[^}]+\}/, '')
    .replace(',', '')
    .trim();
  if (defaultImportPart) {
    identifiers.push(defaultImportPart);
  }

  return identifiers;
}

export function removeUnusedImports(content: string) {
  const lines = content.split('\n');
  const importLineRegex = /^import\s+(.+?)\s+from\s+['"][^'"]+['"];?\s*$/;
  const nonImportContent = lines
    .filter((line) => !importLineRegex.test(line))
    .join('\n');

  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    const importMatch = line.match(importLineRegex);

    if (!importMatch) {
      continue;
    }

    const identifiers = extractImportedIdentifiers(importMatch[1]);
    if (identifiers.length === 0) {
      continue;
    }

    const isUsed = identifiers.some((identifier) => {
      const usageRegex = new RegExp(`\\b${escapeRegExp(identifier)}\\b`, 'm');
      return usageRegex.test(nonImportContent);
    });

    if (!isUsed) {
      lines[index] = '';
    }
  }

  const cleaned = lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd();

  return `${cleaned}\n`;
}

export function replaceSinceTags(content: string) {
  return content.replace(
    /<SinceTag\s+message=("([^"]+)"|'([^']+)')\s*\/>/g,
    (_fullMatch, _messageAttr, doubleQuotedValue, singleQuotedValue) => {
      const version = doubleQuotedValue ?? singleQuotedValue;
      return `Example is supported since version ${version}`;
    }
  );
}

function buildTypographySnippetBlock(format: string) {
  return [
    'HTML:',
    '```html',
    `<ix-typography format="${format}"></ix-typography>`,
    '```',
    '',
    'Angular:',
    '```html',
    `<ix-typography format="${format}"></ix-typography>`,
    '```',
    '',
    'Angular standalone:',
    '```html',
    `<ix-typography format="${format}"></ix-typography>`,
    '```',
    '',
    'React:',
    '```jsx',
    `<IxTypography format="${format}"></IxTypography>`,
    '```',
    '',
    'Vue:',
    '```vue',
    `<IxTypography format="${format}"></IxTypography>`,
    '```',
  ].join('\n');
}

export function replaceTypographyTablesWithMarkdown(content: string) {
  const typographyTableRegex =
    /<TypographyTable\b[^>]*typographyName=("([^"]+)"|'([^']+)')[^>]*\/?>(?:<\/TypographyTable>)?/g;

  return content.replace(
    typographyTableRegex,
    (_fullMatch, _attr, doubleQuoted, singleQuoted) => {
      const format = doubleQuoted ?? singleQuoted;
      if (!format) {
        return _fullMatch;
      }

      return buildTypographySnippetBlock(format);
    }
  );
}

function cleanApiValue(value: string) {
  let cleanedValue = value
    .replace(/<ReactMarkdown>/g, '')
    .replace(/<\/ReactMarkdown>/g, '')
    .replace(/\{`([\s\S]*?)`\}/g, '$1')
    .replace(/<DeprecatedTag\s*\/?>/g, 'Deprecated')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ');

  cleanedValue = replaceSinceTags(cleanedValue);
  return cleanedValue.trim();
}

function parseApiTableBlock(block: string) {
  const row: Record<string, string> = {};

  const headerMatch = block.match(
    /<ApiTable\.(\w+)Header\b[^>]*name=("([^"]+)"|'([^']+)')[^>]*>([\s\S]*?)<\/ApiTable\.\1Header>/
  );

  if (headerMatch) {
    const headerName = headerMatch[3] ?? headerMatch[4] ?? '';
    const headerInner = cleanApiValue(headerMatch[5] ?? '');
    row.Name = headerName;

    if (headerInner) {
      row.Notes = headerInner;
    }
  }

  const fieldRegex =
    /<ApiTable\.(Text|Code)\b[^>]*name=("([^"]+)"|'([^']+)')[^>]*>([\s\S]*?)<\/ApiTable\.\1>/g;

  for (const fieldMatch of block.matchAll(fieldRegex)) {
    const fieldName = fieldMatch[3] ?? fieldMatch[4] ?? '';
    const fieldValue = cleanApiValue(fieldMatch[5] ?? '');

    if (fieldName && fieldValue) {
      row[fieldName] = fieldValue;
    }
  }

  return Object.keys(row).length > 0 ? row : null;
}

function escapeMarkdownTableValue(value: string) {
  return value.replace(/\|/g, '\\|').replace(/\n/g, '<br/>');
}

function rowsToMarkdownTable(rows: Array<Record<string, string>>) {
  if (rows.length === 0) {
    return '';
  }

  const preferredOrder = [
    'Name',
    'Description',
    'Attribute',
    'Type',
    'Default',
    'Event',
    'Detail',
    'Notes',
  ];

  const existingColumns = new Set<string>();
  for (const row of rows) {
    Object.keys(row).forEach((key) => existingColumns.add(key));
  }

  const orderedColumns = preferredOrder.filter((key) =>
    existingColumns.has(key)
  );
  const remainingColumns = [...existingColumns]
    .filter((key) => !orderedColumns.includes(key))
    .sort();
  const columns = [...orderedColumns, ...remainingColumns];

  if (columns.length === 0) {
    return '';
  }

  const header = `| ${columns.join(' | ')} |`;
  const separator = `| ${columns.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => {
    const values = columns.map((column) =>
      escapeMarkdownTableValue((row[column] ?? '').trim())
    );
    return `| ${values.join(' | ')} |`;
  });

  return [header, separator, ...body].join('\n');
}

export function replaceApiTablesWithMarkdown(content: string) {
  const apiTableGroupRegex = /(?:<ApiTable\b[\s\S]*?<\/ApiTable>\s*)+/g;

  return content.replace(apiTableGroupRegex, (group) => {
    const blocks = [...group.matchAll(/<ApiTable\b[\s\S]*?<\/ApiTable>/g)].map(
      (match) => match[0]
    );

    const rows = blocks
      .map((block) => parseApiTableBlock(block))
      .filter((row): row is Record<string, string> => !!row);

    const table = rowsToMarkdownTable(rows);
    if (!table) {
      return group;
    }

    return `${table}\n\n`;
  });
}

function extractAttributeValue(block: string, attribute: string) {
  const match = block.match(
    new RegExp(`${attribute}\\s*=\\s*("([^"]*)"|'([^']*)')`)
  );
  return match?.[2] ?? match?.[3] ?? null;
}

function parseApiFunctionParameters(block: string) {
  const paramsBlockMatch = block.match(
    /parameters\s*=\s*\{?\s*\[([\s\S]*?)\]\s*\}?/
  );
  if (!paramsBlockMatch) {
    return '';
  }

  const paramsBlock = paramsBlockMatch[1];
  const params: string[] = [];

  const objectRegex = /\{([\s\S]*?)\}/g;
  for (const objectMatch of paramsBlock.matchAll(objectRegex)) {
    const objectContent = objectMatch[1];
    const paramNameMatch = objectContent.match(/name\s*:\s*['"]([^'"]+)['"]/);
    const paramTypeMatch = objectContent.match(/type\s*:\s*['"]([^'"]+)['"]/);

    if (paramNameMatch && paramTypeMatch) {
      params.push(`${paramNameMatch[1]}: ${paramTypeMatch[1]}`);
    }
  }

  return params.join(', ');
}

function cleanApiFunctionBody(value: string) {
  return value
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function replaceApiFunctionsWithMarkdown(content: string) {
  const apiFunctionRegex =
    /<ApiFunction\b[\s\S]*?(?:<\/ApiFunction>|(?=\n##\s)|(?=\n###\s)|$)/g;

  return content.replace(apiFunctionRegex, (fullBlock) => {
    const functionName = extractAttributeValue(fullBlock, 'name');
    const returnType = extractAttributeValue(fullBlock, 'returnType') ?? 'void';

    if (!functionName) {
      return fullBlock;
    }

    const parameters = parseApiFunctionParameters(fullBlock);
    const bodyMatch =
      fullBlock.match(/>\s*([\s\S]*?)\s*<\/ApiFunction>/) ??
      fullBlock.match(/>\s*([\s\S]*?)\s*$/);
    const description = cleanApiFunctionBody(bodyMatch?.[1] ?? '');

    const lines = [
      `#### ${functionName}`,
      '',
      '```ts',
      `${functionName}(${parameters}): ${returnType};`,
      '```',
    ];

    if (description) {
      lines.push('', description);
    }

    lines.push('');
    return lines.join('\n');
  });
}
