import { readFile } from 'node:fs/promises';
import path from 'node:path';
import type { FilesMap } from '../types';
import { fileExists } from './filesystem';

const FRAMEWORK_TITLES: Record<string, string> = {
  react: 'React Examples',
  angular: 'Angular Examples',
  angular_standalone: 'Angular Standalone Examples',
  vue: 'Vue Examples',
  html: 'HTML Examples',
};

const FRAMEWORK_ORDER = [
  'react',
  'angular',
  'angular_standalone',
  'vue',
  'html',
];

function extractObjectLiteral(source: string, token: string) {
  const tokenIndex = source.indexOf(token);
  if (tokenIndex === -1) {
    return null;
  }

  const objectStart = tokenIndex + token.length;
  if (source.slice(objectStart, objectStart + 2) !== '{{') {
    return null;
  }

  let depth = 0;
  let hasStarted = false;

  for (let index = objectStart; index < source.length; index++) {
    const char = source[index];

    if (char === '{') {
      depth += 1;
      hasStarted = true;
    }

    if (char === '}') {
      depth -= 1;
      if (hasStarted && depth === 0) {
        return source.slice(objectStart, index + 1);
      }
    }
  }

  return null;
}

export function parseFilesMap(input: string): FilesMap {
  const filesObjectLiteral = extractObjectLiteral(input, 'files=');
  if (!filesObjectLiteral) {
    return {};
  }

  const inner = filesObjectLiteral.slice(2, -2);
  const map: FilesMap = {};

  const frameworkRegex = /(\w+)\s*:\s*\{([\s\S]*?)\}(?:,|$)/g;
  for (const frameworkMatch of inner.matchAll(frameworkRegex)) {
    const framework = frameworkMatch[1];
    const frameworkBody = frameworkMatch[2];

    const fileNames: string[] = [];
    const fileRegex = /'([^']+)'\s*:\s*'[^']+'/g;

    for (const fileMatch of frameworkBody.matchAll(fileRegex)) {
      fileNames.push(fileMatch[1]);
    }

    if (fileNames.length > 0) {
      map[framework] = fileNames;
    }
  }

  return map;
}

export function getOnlyFramework(input: string) {
  const onlyFrameworkMatch = input.match(/onlyFramework\s*=\s*"([^"]+)"/);
  return onlyFrameworkMatch?.[1];
}

async function readUsageSnippet(
  siteDir: string,
  framework: string,
  fileName: string
): Promise<string | null> {
  const usagePath = path.join(
    siteDir,
    'docs',
    'autogenerated',
    'usage',
    framework,
    `${fileName}.md`
  );

  if (!(await fileExists(usagePath))) {
    return null;
  }

  const content = await readFile(usagePath, 'utf8');
  return content.trim();
}

export async function buildMarkdownFromFilesMap(
  siteDir: string,
  filesMap: FilesMap,
  options?: { onlyFramework?: string; alwaysUseFrameworkHeading?: boolean }
) {
  const frameworks = FRAMEWORK_ORDER.filter(
    (framework) => !!filesMap[framework]
  );

  const filteredFrameworks = options?.onlyFramework
    ? frameworks.filter((framework) => framework === options.onlyFramework)
    : frameworks;

  if (filteredFrameworks.length === 0) {
    return '';
  }

  const showFrameworkHeadings =
    options?.alwaysUseFrameworkHeading ?? filteredFrameworks.length > 1;

  const markdownSections: string[] = [];

  for (const framework of filteredFrameworks) {
    const files = filesMap[framework] ?? [];
    const snippets = await Promise.all(
      files.map((fileName) => readUsageSnippet(siteDir, framework, fileName))
    );

    const resolvedSnippets = files
      .map((fileName, index) => ({
        fileName,
        snippet: snippets[index],
      }))
      .filter((entry) => !!entry.snippet);

    if (resolvedSnippets.length === 0) {
      continue;
    }

    if (showFrameworkHeadings) {
      markdownSections.push(`### ${FRAMEWORK_TITLES[framework] ?? framework}`);
      markdownSections.push('');
    }

    for (const entry of resolvedSnippets) {
      markdownSections.push(`#### ${entry.fileName}`);
      markdownSections.push(entry.snippet!);
      markdownSections.push('');
    }
  }

  return markdownSections.join('\n').trim();
}
