import * as mdx from 'eslint-plugin-mdx';
import markupIndent from './scripts/eslint-rules/markup-indent.mjs';

export default [
  {
    ignores: ['docs/autogenerated/**'],
  },
  {
    ...mdx.flat,
    files: ['**/*.{md,mdx}'],
    plugins: {
      ...mdx.flat.plugins,
      local: {
        rules: {
          'markup-indent': markupIndent,
        },
      },
    },
    rules: {
      ...mdx.flat.rules,
      'local/markup-indent': 'error',
    },
  },
];
