/*
 * COPYRIGHT (c) Siemens AG 2018-2026 ALL RIGHTS RESERVED.
 */
import type { LoadContext } from '@docusaurus/types';
import { access } from 'node:fs/promises';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { glob } from 'glob';

type FilesMap = Record<string, string[]>;

const FRAMEWORK_TITLES: Record<string, string> = {
  react: 'React',
  angular: 'Angular',
  angular_standalone: 'Angular Standalone',
  vue: 'Vue',
  html: 'HTML',
};

const FRAMEWORK_ORDER = [
  'react',
  'angular',
  'angular_standalone',
  'vue',
  'html',
];

async function fileExists(filePath: string) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function waitForFiles(
  files: string[],
  timeoutMs = 15000,
  intervalMs = 250,
) {
  const startTime = Date.now();

  while (Date.now() - startTime < timeoutMs) {
    const results = await Promise.all(files.map(fileExists));
    if (results.every(Boolean)) {
      return true;
    }

    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }

  return false;
}

function extractObjectLiteral(source: string, token: string) {
  const tokenIndex = source.indexOf(token);
  if (tokenIndex === -1) {
    return null;
  }

  const objectStart = tokenIndex + token.length;
  if (source.slice(objectStart, objectStart + 2) !== '{{') {
    return null;
  }

  let depth = 0;
  let hasStarted = false;

  for (let index = objectStart; index < source.length; index++) {
    const char = source[index];

    if (char === '{') {
      depth += 1;
      hasStarted = true;
    }

    if (char === '}') {
      depth -= 1;
      if (hasStarted && depth === 0) {
        return source.slice(objectStart, index + 1);
      }
    }
  }

  return null;
}

function parseFilesMap(input: string): FilesMap {
  const filesObjectLiteral = extractObjectLiteral(input, 'files=');
  if (!filesObjectLiteral) {
    return {};
  }

  const inner = filesObjectLiteral.slice(2, -2);
  const map: FilesMap = {};

  const frameworkRegex = /(\w+)\s*:\s*\{([\s\S]*?)\}(?:,|$)/g;
  for (const frameworkMatch of inner.matchAll(frameworkRegex)) {
    const framework = frameworkMatch[1];
    const frameworkBody = frameworkMatch[2];

    const fileNames: string[] = [];
    const fileRegex = /'([^']+)'\s*:\s*'[^']+'/g;

    for (const fileMatch of frameworkBody.matchAll(fileRegex)) {
      fileNames.push(fileMatch[1]);
    }

    if (fileNames.length > 0) {
      map[framework] = fileNames;
    }
  }

  return map;
}

function getOnlyFramework(input: string) {
  const onlyFrameworkMatch = input.match(/onlyFramework\s*=\s*"([^"]+)"/);
  return onlyFrameworkMatch?.[1];
}

function renderLanguageLabel(fileName: string) {
  return fileName;
}

async function readUsageSnippet(
  siteDir: string,
  framework: string,
  fileName: string,
): Promise<string | null> {
  const usagePath = path.join(
    siteDir,
    'docs',
    'autogenerated',
    'usage',
    framework,
    `${fileName}.md`,
  );

  if (!(await fileExists(usagePath))) {
    return null;
  }

  const content = await readFile(usagePath, 'utf8');
  return content.trim();
}

async function buildMarkdownFromFilesMap(
  siteDir: string,
  filesMap: FilesMap,
  options?: { onlyFramework?: string; alwaysUseFrameworkHeading?: boolean },
) {
  const frameworks = FRAMEWORK_ORDER.filter(
    (framework) => !!filesMap[framework],
  );

  const filteredFrameworks = options?.onlyFramework
    ? frameworks.filter((framework) => framework === options.onlyFramework)
    : frameworks;

  if (filteredFrameworks.length === 0) {
    return '';
  }

  const showFrameworkHeadings =
    options?.alwaysUseFrameworkHeading ?? filteredFrameworks.length > 1;

  const markdownSections: string[] = [];

  for (const framework of filteredFrameworks) {
    const files = filesMap[framework] ?? [];
    const snippets = await Promise.all(
      files.map((fileName) => readUsageSnippet(siteDir, framework, fileName)),
    );

    const resolvedSnippets = files
      .map((fileName, index) => ({
        fileName,
        snippet: snippets[index],
      }))
      .filter((entry) => !!entry.snippet);

    if (resolvedSnippets.length === 0) {
      continue;
    }

    if (showFrameworkHeadings) {
      markdownSections.push(`### ${FRAMEWORK_TITLES[framework] ?? framework}`);
      markdownSections.push('');
    }

    for (const entry of resolvedSnippets) {
      markdownSections.push(`#### ${renderLanguageLabel(entry.fileName)}`);
      markdownSections.push(entry.snippet!);
      markdownSections.push('');
    }
  }

  return markdownSections.join('\n').trim();
}

function extractPlaygroundImports(content: string) {
  const imports = new Map<string, string>();

  const regex =
    /import\s+(\w+)\s+from\s+'@site\/docs\/autogenerated\/playground\/([^']+)\.mdx';?/g;

  for (const match of content.matchAll(regex)) {
    imports.set(match[1], match[2]);
  }

  return imports;
}

function extractAutogeneratedMdxImports(content: string) {
  const imports = new Map<string, string>();

  const regex =
    /import\s+(\w+)\s+from\s+'@site\/docs\/autogenerated\/([^']+)\.mdx';?/g;

  for (const match of content.matchAll(regex)) {
    imports.set(match[1], match[2]);
  }

  return imports;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function extractImportedIdentifiers(importClause: string) {
  const identifiers: string[] = [];
  const clause = importClause.trim();

  const namedImportMatch = clause.match(/\{([^}]+)\}/);
  if (namedImportMatch) {
    const namedImports = namedImportMatch[1]
      .split(',')
      .map((token) => token.trim())
      .filter(Boolean);

    for (const token of namedImports) {
      const aliasMatch = token.match(/^\w+\s+as\s+(\w+)$/);
      if (aliasMatch) {
        identifiers.push(aliasMatch[1]);
      } else {
        identifiers.push(token);
      }
    }
  }

  const defaultImportPart = clause
    .replace(/\{[^}]+\}/, '')
    .replace(',', '')
    .trim();
  if (defaultImportPart) {
    identifiers.push(defaultImportPart);
  }

  return identifiers;
}

function removeUnusedImports(content: string) {
  const lines = content.split('\n');
  const importLineRegex = /^import\s+(.+?)\s+from\s+['"][^'"]+['"];?\s*$/;
  const nonImportContent = lines
    .filter((line) => !importLineRegex.test(line))
    .join('\n');

  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    const importMatch = line.match(importLineRegex);

    if (!importMatch) {
      continue;
    }

    const identifiers = extractImportedIdentifiers(importMatch[1]);
    if (identifiers.length === 0) {
      continue;
    }

    const isUsed = identifiers.some((identifier) => {
      const usageRegex = new RegExp(`\\b${escapeRegExp(identifier)}\\b`, 'm');
      return usageRegex.test(nonImportContent);
    });

    if (!isUsed) {
      lines[index] = '';
    }
  }

  const cleaned = lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd();

  return `${cleaned}\n`;
}

function replaceSinceTags(content: string) {
  return content.replace(
    /<SinceTag\s+message=("([^"]+)"|'([^']+)')\s*\/>/g,
    (_fullMatch, _messageAttr, doubleQuotedValue, singleQuotedValue) => {
      const version = doubleQuotedValue ?? singleQuotedValue;
      return `Example is supported since version ${version}`;
    },
  );
}

function cleanApiValue(value: string) {
  return value
    .replace(/<ReactMarkdown>/g, '')
    .replace(/<\/ReactMarkdown>/g, '')
    .replace(/\{`([\s\S]*?)`\}/g, '$1')
    .replace(
      /<SinceTag\s+message=("([^"]+)"|'([^']+)')\s*\/>/g,
      (_m, _a, d, s) => {
        const version = d ?? s;
        return `Example is supported since version ${version}`;
      },
    )
    .replace(/<DeprecatedTag\s*\/?>/g, 'Deprecated')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseApiTableBlock(block: string) {
  const row: Record<string, string> = {};

  const headerMatch = block.match(
    /<ApiTable\.(\w+)Header\b[^>]*name=("([^"]+)"|'([^']+)')[^>]*>([\s\S]*?)<\/ApiTable\.\1Header>/,
  );

  if (headerMatch) {
    const headerName = headerMatch[3] ?? headerMatch[4] ?? '';
    const headerInner = cleanApiValue(headerMatch[5] ?? '');
    row.Name = headerName;

    if (headerInner) {
      row.Notes = headerInner;
    }
  }

  const fieldRegex =
    /<ApiTable\.(Text|Code)\b[^>]*name=("([^"]+)"|'([^']+)')[^>]*>([\s\S]*?)<\/ApiTable\.\1>/g;

  for (const fieldMatch of block.matchAll(fieldRegex)) {
    const fieldName = fieldMatch[3] ?? fieldMatch[4] ?? '';
    const fieldValue = cleanApiValue(fieldMatch[5] ?? '');

    if (fieldName && fieldValue) {
      row[fieldName] = fieldValue;
    }
  }

  return Object.keys(row).length > 0 ? row : null;
}

function escapeMarkdownTableValue(value: string) {
  return value.replace(/\|/g, '\\|').replace(/\n/g, '<br/>');
}

function rowsToMarkdownTable(rows: Array<Record<string, string>>) {
  if (rows.length === 0) {
    return '';
  }

  const preferredOrder = [
    'Name',
    'Description',
    'Attribute',
    'Type',
    'Default',
    'Event',
    'Detail',
    'Notes',
  ];

  const existingColumns = new Set<string>();
  for (const row of rows) {
    Object.keys(row).forEach((key) => existingColumns.add(key));
  }

  const orderedColumns = preferredOrder.filter((key) =>
    existingColumns.has(key),
  );
  const remainingColumns = [...existingColumns]
    .filter((key) => !orderedColumns.includes(key))
    .sort();
  const columns = [...orderedColumns, ...remainingColumns];

  if (columns.length === 0) {
    return '';
  }

  const header = `| ${columns.join(' | ')} |`;
  const separator = `| ${columns.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => {
    const values = columns.map((column) =>
      escapeMarkdownTableValue((row[column] ?? '').trim()),
    );
    return `| ${values.join(' | ')} |`;
  });

  return [header, separator, ...body].join('\n');
}

function replaceApiTablesWithMarkdown(content: string) {
  const apiTableGroupRegex = /(?:<ApiTable\b[\s\S]*?<\/ApiTable>\s*)+/g;

  return content.replace(apiTableGroupRegex, (group) => {
    const blocks = [...group.matchAll(/<ApiTable\b[\s\S]*?<\/ApiTable>/g)].map(
      (match) => match[0],
    );

    const rows = blocks
      .map((block) => parseApiTableBlock(block))
      .filter((row): row is Record<string, string> => !!row);

    const table = rowsToMarkdownTable(rows);
    if (!table) {
      return group;
    }

    return `${table}\n\n`;
  });
}

export default function (context: LoadContext) {
  return {
    name: 'llmstxt-postbuild',

    async postBuild() {
      const { outDir, siteDir } = context;
      console.log(`Post-build: Output directory is ${outDir}`);

      const llmsFiles = [
        path.join(outDir, 'llms.txt'),
        path.join(outDir, 'llms-full.txt'),
      ];

      const llmsReady = await waitForFiles(llmsFiles);
      if (!llmsReady) {
        throw new Error(
          `llms output not ready in time. Expected files: ${llmsFiles.join(', ')}`,
        );
      }

      const pattern = `${outDir}/docs/components/**/code.md`;
      console.log(`Searching for generated code docs with pattern: ${pattern}`);

      try {
        const files = await glob(pattern);
        console.log(`Found ${files.length} generated code docs`);

        const playgroundMdxCache = new Map<string, string>();
        const autogeneratedMdxCache = new Map<string, string>();
        let updatedFiles = 0;

        for (const filePath of files) {
          const originalContent = await readFile(filePath, 'utf8');
          let nextContent = originalContent;

          const playgroundImports = extractPlaygroundImports(originalContent);

          for (const [
            componentName,
            playgroundName,
          ] of playgroundImports.entries()) {
            const tagRegex = new RegExp(`<${componentName}\\b[^>]*\\/>`, 'g');
            if (!tagRegex.test(nextContent)) {
              continue;
            }

            let playgroundMdx = playgroundMdxCache.get(playgroundName);
            if (!playgroundMdx) {
              const playgroundPath = path.join(
                siteDir,
                'docs',
                'autogenerated',
                'playground',
                `${playgroundName}.mdx`,
              );

              if (!(await fileExists(playgroundPath))) {
                continue;
              }

              playgroundMdx = await readFile(playgroundPath, 'utf8');
              playgroundMdxCache.set(playgroundName, playgroundMdx);
            }

            const filesMap = parseFilesMap(playgroundMdx);
            const replacement = await buildMarkdownFromFilesMap(
              siteDir,
              filesMap,
            );

            if (replacement) {
              nextContent = nextContent.replace(tagRegex, replacement);
            }
          }

          const inlinePlaygroundRegex = /<Playground\b[\s\S]*?><\/Playground>/g;
          const inlinePlaygroundBlocks = [
            ...nextContent.matchAll(inlinePlaygroundRegex),
          ];

          for (const match of inlinePlaygroundBlocks) {
            const playgroundBlock = match[0];
            const filesMap = parseFilesMap(playgroundBlock);
            const onlyFramework = getOnlyFramework(playgroundBlock);

            const replacement = await buildMarkdownFromFilesMap(
              siteDir,
              filesMap,
              {
                onlyFramework,
              },
            );

            if (replacement) {
              nextContent = nextContent.replace(playgroundBlock, replacement);
            }
          }

          const autogeneratedImports =
            extractAutogeneratedMdxImports(nextContent);

          for (const [
            componentName,
            mdxRelativePath,
          ] of autogeneratedImports.entries()) {
            const selfClosingTagRegex = new RegExp(
              `<${componentName}\\b[^>]*\\/>`,
              'g',
            );
            const pairedTagRegex = new RegExp(
              `<${componentName}\\b[^>]*>[\\s\\S]*?<\\/${componentName}>`,
              'g',
            );

            if (
              !selfClosingTagRegex.test(nextContent) &&
              !pairedTagRegex.test(nextContent)
            ) {
              continue;
            }

            let mdxContent = autogeneratedMdxCache.get(mdxRelativePath);
            if (!mdxContent) {
              const mdxPath = path.join(
                siteDir,
                'docs',
                'autogenerated',
                `${mdxRelativePath}.mdx`,
              );

              if (!(await fileExists(mdxPath))) {
                continue;
              }

              mdxContent = (await readFile(mdxPath, 'utf8')).trim();
              autogeneratedMdxCache.set(mdxRelativePath, mdxContent);
            }

            nextContent = nextContent
              .replace(selfClosingTagRegex, mdxContent)
              .replace(pairedTagRegex, mdxContent);
          }

          nextContent = replaceSinceTags(nextContent);
          nextContent = replaceApiTablesWithMarkdown(nextContent);

          if (nextContent !== originalContent) {
            nextContent = removeUnusedImports(nextContent);
            await writeFile(filePath, nextContent, 'utf8');
            updatedFiles += 1;
          }
        }

        console.log(
          `Updated ${updatedFiles} generated code docs with inline examples`,
        );
      } catch (error) {
        console.error('Error during post-build processing:', error);
      }
    },
  };
}
