import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { glob } from 'glob';
import { waitForFiles, fileExists } from './utils/filesystem';
import {
  buildMarkdownFromFilesMap,
  getOnlyFramework,
  parseFilesMap,
} from './utils/playground';
import {
  extractAutogeneratedMdxImports,
  extractPlaygroundImports,
  removeUnusedImports,
  replaceApiFunctionsWithMarkdown,
  replaceApiTablesWithMarkdown,
  replaceSinceTags,
} from './utils/content-transforms';

type PostBuildArgs = {
  outDir: string;
  siteDir: string;
};

export async function runPostBuild({ outDir, siteDir }: PostBuildArgs) {
  console.log(`Post-build: Output directory is ${outDir}`);

  const llmsFiles = [
    path.join(outDir, 'llms.txt'),
    path.join(outDir, 'llms-full.txt'),
  ];

  const llmsReady = await waitForFiles(llmsFiles);
  if (!llmsReady) {
    throw new Error(
      `llms output not ready in time. Expected files: ${llmsFiles.join(', ')}`,
    );
  }

  const pattern = `${outDir}/docs/components/**/*.md`;
  console.log(`Searching for generated component docs with pattern: ${pattern}`);

  const files = await glob(pattern);
  console.log(`Found ${files.length} generated component docs`);

  const playgroundMdxCache = new Map<string, string>();
  const autogeneratedMdxCache = new Map<string, string>();
  let updatedFiles = 0;

  for (const filePath of files) {
    const originalContent = await readFile(filePath, 'utf8');
    let nextContent = originalContent;

    const playgroundImports = extractPlaygroundImports(originalContent);

    for (const [componentName, playgroundName] of playgroundImports.entries()) {
      const tagRegex = new RegExp(`<${componentName}\\b[^>]*\\/>`, 'g');
      if (!tagRegex.test(nextContent)) {
        continue;
      }

      let playgroundMdx = playgroundMdxCache.get(playgroundName);
      if (!playgroundMdx) {
        const playgroundPath = path.join(
          siteDir,
          'docs',
          'autogenerated',
          'playground',
          `${playgroundName}.mdx`,
        );

        if (!(await fileExists(playgroundPath))) {
          continue;
        }

        playgroundMdx = await readFile(playgroundPath, 'utf8');
        playgroundMdxCache.set(playgroundName, playgroundMdx);
      }

      const filesMap = parseFilesMap(playgroundMdx);
      const replacement = await buildMarkdownFromFilesMap(siteDir, filesMap);

      if (replacement) {
        nextContent = nextContent.replace(tagRegex, replacement);
      }
    }

    const inlinePlaygroundRegex = /<Playground\b[\s\S]*?><\/Playground>/g;
    const inlinePlaygroundBlocks = [...nextContent.matchAll(inlinePlaygroundRegex)];

    for (const match of inlinePlaygroundBlocks) {
      const playgroundBlock = match[0];
      const filesMap = parseFilesMap(playgroundBlock);
      const onlyFramework = getOnlyFramework(playgroundBlock);

      const replacement = await buildMarkdownFromFilesMap(siteDir, filesMap, {
        onlyFramework,
      });

      if (replacement) {
        nextContent = nextContent.replace(playgroundBlock, replacement);
      }
    }

    const autogeneratedImports = extractAutogeneratedMdxImports(nextContent);

    for (const [componentName, mdxRelativePath] of autogeneratedImports.entries()) {
      const selfClosingTagRegex = new RegExp(`<${componentName}\\b[^>]*\\/>`, 'g');
      const pairedTagRegex = new RegExp(
        `<${componentName}\\b[^>]*>[\\s\\S]*?<\\/${componentName}>`,
        'g',
      );

      if (
        !selfClosingTagRegex.test(nextContent) &&
        !pairedTagRegex.test(nextContent)
      ) {
        continue;
      }

      let mdxContent = autogeneratedMdxCache.get(mdxRelativePath);
      if (!mdxContent) {
        const mdxPath = path.join(
          siteDir,
          'docs',
          'autogenerated',
          `${mdxRelativePath}.mdx`,
        );

        if (!(await fileExists(mdxPath))) {
          continue;
        }

        mdxContent = (await readFile(mdxPath, 'utf8')).trim();
        autogeneratedMdxCache.set(mdxRelativePath, mdxContent);
      }

      nextContent = nextContent
        .replace(selfClosingTagRegex, mdxContent)
        .replace(pairedTagRegex, mdxContent);
    }

    nextContent = replaceSinceTags(nextContent);
    nextContent = replaceApiTablesWithMarkdown(nextContent);
    nextContent = replaceApiFunctionsWithMarkdown(nextContent);

    if (nextContent !== originalContent) {
      nextContent = removeUnusedImports(nextContent);
      await writeFile(filePath, nextContent, 'utf8');
      updatedFiles += 1;
    }
  }

  console.log(
    `Updated ${updatedFiles} generated component docs with inline examples`,
  );
}
