/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { config as dotenv } from '@dotenvx/dotenvx';
import { Octokit } from '@octokit/rest';
import AdmZip from 'adm-zip';
import fs from 'fs-extra';
import os from 'os';
import path from 'path';
import { glob } from 'glob';
import copyTheme from './copy-theme';

const __dirname = path.resolve();

dotenv({
  path: path.join(__dirname, '.env'),
});

dotenv({
  path: path.join(__dirname, '.env.production'),
});

dotenv({
  path: path.join(__dirname, '.env.pullrequest'),
  override: true,
});

const __temp = path.join(os.tmpdir(), 'ix-docs');
const __promptDefaults = path.join(__temp, 'defaults.json');

type BranchConfig = {
  branch: string;
  branchType: 'main' | 'pull request' | (string & {});
  prNumber: string;
};

const autogeneratedImportPattern =
  /@site\/docs\/autogenerated\/(api|playground)\/([^"']+)/g;

async function getDefaultFile() {
  if (!(await fs.exists(__promptDefaults))) {
    return {};
  }

  const defaults = JSON.parse(await fs.readFile(__promptDefaults, 'utf8'));
  return defaults;
}

async function getDefaults(): Promise<BranchConfig> {
  let defaults: BranchConfig = {
    branch: 'main',
    branchType: 'main',
    prNumber: '',
  };

  if (
    !(
      process.env.IX_REPO_BRANCH &&
      process.env.IX_REPO_TYPE &&
      process.env.IX_REPO_PR !== undefined
    )
  ) {
    throw new Error(
      'IX_REPO_BRANCH, IX_REPO_TYPE and IX_REPO_PR environment variables are required in CI.'
    );
  }

  defaults.branch = process.env.IX_REPO_BRANCH;
  defaults.branchType = process.env.IX_REPO_TYPE;
  defaults.prNumber = process.env.IX_REPO_PR;

  return defaults;
}

async function main() {
  if (process.env.SKIP_PREPARE) {
    console.log('========================================');
    console.log('===      SKIPPING PREPARE STEP       ===');
    console.log('========================================');
    console.log(`Reason: SKIP_PREPARE is set to "${process.env.SKIP_PREPARE}"`);
    await ensureAutogeneratedFallback('SKIP_PREPARE');
    return;
  }
  const defaults = await getDefaults();

  console.log('Script will start with the following defaults:');
  console.log(`Branch: ${defaults.branch}`);
  console.log(`Branch Type: ${defaults.branchType}`);
  console.log(`PR Number: ${defaults.prNumber}`);

  await copyTheme();

  const branch = getBranch(defaults);

  try {
    await downloadLatestArtifact(branch);
  } catch (error) {
    if (process.env.CI) {
      throw error;
    }

    console.warn('Falling back to local autogenerated placeholders.');
    console.warn(error);
    await ensureAutogeneratedFallback('artifact download failed');
  }
}

function getBranch(config: BranchConfig) {
  if (config.branchType === 'pull request') {
    return `pull/${config.prNumber}`;
  }
  return config.branch;
}

async function downloadLatestArtifact(branch: string) {
  const repo = 'ix';
  const owner = 'siemens';
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    const message = [
      'GITHUB_TOKEN environment variable is not set.',
      '',
      '',
      '⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️',
      'Please set the GITHUB_TOKEN environment variable to a valid GitHub token.',
      `You can create a new token at https://github.com/settings/personal-access-tokens,`,
      'the token must not have any permissions.',
      '⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️',
      '',
      '',
    ];

    throw new Error(message.join('\n'));
  }
  const octokit = new Octokit({ auth: token });

  // For PRs, get the head branch name
  let branchName = branch;
  if (branch.startsWith('pull/')) {
    const prNumber = parseInt(branch.split('/')[1], 10);
    const { data: pr } = await octokit.pulls.get({
      owner,
      repo,
      pull_number: prNumber,
    });
    branchName = pr.head.ref;
  }

  const eventRuns = await Promise.all([
    octokit.actions.listWorkflowRunsForRepo({
      owner,
      repo,
      branch: branchName,
      event: 'workflow_dispatch',
    }),
    octokit.actions.listWorkflowRunsForRepo({
      owner,
      repo,
      branch: branchName,
      event: 'push',
    }),
    octokit.actions.listWorkflowRunsForRepo({
      owner,
      repo,
      branch: branchName,
      event: 'pull_request',
    }),
  ]);

  const runs = eventRuns
    .flatMap((run) => run.data.workflow_runs)
    .sort(
      (a, b) =>
        new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
    );

  if (
    !runs ||
    runs.length === 0 ||
    runs.filter((run) => run.name === 'Build' || run.name === 'Pull Request')
      .length === 0
  ) {
    const message = `No workflow runs found for this branch. ${branchName}`;
    throw new Error(message);
  }
  const runId = runs.filter(
    (run) => run.name === 'Build' || run.name === 'Pull Request'
  )[0].id;

  // Get artifacts for the run
  const { data: artifactsData } =
    await octokit.actions.listWorkflowRunArtifacts({
      owner,
      repo,
      run_id: runId,
    });

  if (!artifactsData.artifacts || artifactsData.artifacts.length === 0) {
    throw new Error('No artifacts found for this workflow run.');
  }

  const artifact = artifactsData.artifacts.find((artifact) =>
    artifact.name.startsWith('documentation-')
  );

  if (!artifact) {
    throw new Error('No documentation artifact found for this workflow run.');
  }

  console.log(
    `Downloading artifact: ${artifact.name} (ID: ${artifact.id})`,
    artifact
  );

  // Download the artifact zip
  const { data: zipData } = await octokit.actions.downloadArtifact({
    owner,
    repo,
    artifact_id: artifact.id,
    archive_format: 'zip',
  });

  // Write zip to temp file
  const tempZipPath = path.join(os.tmpdir(), `artifact-${artifact.id}.zip`);
  await fs.writeFile(tempZipPath, Buffer.from(zipData as ArrayBuffer));

  // Extract artifact
  const zip = new AdmZip(tempZipPath);
  zip.extractAllTo(__dirname, true);

  // Clean up
  await fs.remove(tempZipPath);
}

async function ensureAutogeneratedFallback(reason: string) {
  const missingImports = await findMissingAutogeneratedImports();

  if (missingImports.length === 0) {
    console.log('No autogenerated placeholders needed.');
    return;
  }

  console.log(
    `Creating ${missingImports.length} local autogenerated placeholder files (${reason}).`
  );

  await Promise.all(
    missingImports.map(async (filePath) => {
      await fs.ensureDir(path.dirname(filePath));
      await fs.writeFile(filePath, createPlaceholderContent(filePath), 'utf8');
    })
  );
}

async function findMissingAutogeneratedImports() {
  const docsFiles = await glob('docs/**/*.{md,mdx}', {
    cwd: __dirname,
    absolute: true,
  });

  const missingImports = new Set<string>();

  for (const docsFile of docsFiles) {
    const content = await fs.readFile(docsFile, 'utf8');
    const matches = content.matchAll(autogeneratedImportPattern);

    for (const match of matches) {
      const generatedPath = path.join(
        __dirname,
        'docs',
        'autogenerated',
        match[1],
        match[2]
      );

      if (!(await fs.pathExists(generatedPath))) {
        missingImports.add(generatedPath);
      }
    }
  }

  return [...missingImports].sort();
}

function createPlaceholderContent(filePath: string) {
  const relativePath = path.relative(
    path.join(__dirname, 'docs', 'autogenerated'),
    filePath
  );
  const placeholderType = relativePath.startsWith('api') ? 'API' : 'example';

  return [
    `# ${placeholderType} unavailable`,
    '',
    'This placeholder was generated for a local docs build because the',
    'external autogenerated documentation artifact is unavailable.',
    '',
    `Missing source: ${relativePath}`,
    '',
  ].join('\n');
}

main();
