name: Pull Request

on:
  pull_request:
    branches-ignore:
      - changeset-release/main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build
